jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Buildozer & Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer
          sudo apt update
          sudo apt install -y libtinfo5
          
      - name: Install Android SDK & Accept Licenses
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Build APK
        run: |
          buildozer -v android debug
