name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6 libstdc++6  # Replaced libncurses5 with libncurses6

      - name: Build APK
        uses: digreatbrian/buildozer-action@v1
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: .  # Ensure this points to your `main.py` directory

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
